%% *getFault*
% Get faults for the inversion

%%
% *Input:*

% unknInd - [5, noFltt] index array generated by function 'setUnknowns'
% param   - [1, :] array of the fault-related unknowns

%%
% *Output:*
% fault   - [5, noFlt] array obtained from function 'setFault' and subsequently modified
% noFlt   - the number of faults

%%
% *Author:* Vladimir Grechka 2012 

%%
function [fault, noFlt] = getFault(unknInd, param)
%% Settings 
[~, thisFileName, ~] = fileparts(mfilename('fullpath'));
narginTrue = nargin(thisFileName);   
narginchk(narginTrue, narginTrue);

[fault, noFlt] = setFault;

%% Modify elements of array 'fault' 
[irow, icol] = find(unknInd == 0);
for i = 1:length(irow)
    fault(irow(i), icol(i)) = param(i);                     
end;

end    % of the function