%% *getTau*
% Get the event origin times for the inversion

%%
% *Input:*

% unknInd - [1, noSou] index array generated by function 'setUnknowns'
%   noSou - the number of sources
% param   - [1, :] array of the origin time-related unknowns

%%
% *Output:*

% tau     - [1, noSou] array obtained from function setTau and subsequently modified

%%
% *Author:* Vladimir Grechka 2012 

%%
function [tau] = getTau(unknInd, param)
%% Settings 
[~, thisFileName, ~] = fileparts(mfilename('fullpath'));
narginTrue = nargin(thisFileName);   
narginchk(narginTrue, narginTrue);

noSou = length(unknInd);
tau = setTau(noSou);

%% Modify elements of array 'tau' 
count = 0;
for isou = 1:noSou
    if unknInd(isou) == 0
        count = count + 1;
        tau(isou) = param(count);                       
    end;
end;

end    % of the function