%% *saveFigure*
% Save Matlab figure in .fig, .jpg, and .eps formats

%%
% *Input:*  

% fig        - [scalar] number of an existing figure
% figureName - full figure name, such as generated by Matlab function 'fullfile'
% flag       - [4, 1] array containing ones and zeros to indicate in which formats the figure 
%              is to be saved
%              flag(1)  = 1 - figureName.fig file is to be saved 
%              flag(1) ~= 1 - .fig file is not saved 
%              flag(2)  = 1 - figureName.jpg file is to be saved 
%              flag(2) ~= 1 - .jpg file is not saved 
%              flag(3)  = 1 - figureName.eps file is to be saved 
%              flag(3) ~= 1 - .eps file is not saved  
%              flag(4)  = 1 - figureName.tiff file is to be saved 
%              flag(4) ~= 1 - .tiff file is not saved  

%%
% *Output:* none

%%
% *Comments:* 
%
% * Function |saveFigure| overwrites existing files without asking for permission
%
% * Matlab seems to be unable to save |.fig| files larger than 1GB

%%
% *Author:* Vladimir Grechka 2012 2013

%%
function saveFigure(fig, figureName, flag)
%% Settings and defaults
[thisFolderName, thisFileName, ~] = fileparts(mfilename('fullpath'));
narginTrue = nargin(thisFileName);   
narginchk(narginTrue, narginTrue);

if isempty(flag) == 1
    flag = [0, 0, 0, 0];
end;

%% Make folder for saving the figure if such a folder does not exist
[folderName, fileName, ext] = fileparts(figureName);
if isempty(folderName) == 0  &&  exist(folderName, 'file') == 0
    fprintf('\n>>> Function ''%s'' \n', fullfile(thisFolderName, [thisFileName, '.m']));
    fprintf('>>> Creating folder ''%s'' \n', folderName);
    fprintf('>>>    to save file ''%s'' \n \n', [fileName, ext]);
    mkdir(folderName);
end;

%% Figure setup
figure(fig);
set(gcf, 'PaperPositionMode', 'auto');

if flag(1) == 1
    fprintf('>>> Saving the figure to ''%s'' \n', strcat(figureName, '.fig')); 
    saveas(fig, [figureName, '.fig']);
end;

if length(flag) > 1  &&  flag(2) == 1
    fprintf('>>> Saving the figure to ''%s'' \n', strcat(figureName, '.jpg')); 
    print(fig, '-djpeg',  '-r300', [figureName, '.jpg']);
end;

if length(flag) > 2  &&  flag(3) == 1
    fprintf('>>> Saving the figure to ''%s'' \n', strcat(figureName, '.eps')); 
    print(fig, '-depsc2', '-r300', [figureName, '.eps']);
end;

if length(flag) > 3  &&  flag(4) == 1
    fprintf('>>> Saving the figure to ''%s'' \n', strcat(figureName, '.tif')); 
    print(fig, '-dtiffn', '-r300', [figureName, '.tif']);
end;

end    % of the function
